import React, { useState } from 'react';
import { X, Radio } from 'lucide-react';
import { chatService } from '../../services/chatService';

export const CreateVideoRoomModal: React.FC<{isOpen:boolean;onClose:()=>void;onCreated:(room:any)=>void}> = ({isOpen,onClose,onCreated}) => {
  const [name,setName]=useState(''); const [topic,setTopic]=useState(''); const [maxParticipants,setMax]=useState(8); const [busy,setBusy]=useState(false);
  if(!isOpen)return null;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return;setBusy(true);try{const room=await chatService.createRoom({title:name.trim(),description:topic,topic,type:'video',roomType:'video',isVoice:true,isVideo:true,isLive:true,maxParticipants});onCreated({...room,title:name.trim(),topic,maxParticipants});onClose();}catch(err:any){alert(err.message||'تعذر إنشاء الغرفة');}finally{setBusy(false);}};
  return <div className="fixed inset-0 z-[150] bg-black/70 flex items-center justify-center p-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white dark:bg-slate-950 text-slate-900 dark:text-white border border-slate-200 dark:border-slate-800 p-5 space-y-4"><div className="flex items-center justify-between"><h3 className="font-black flex items-center gap-2"><Radio/> غرفة فيديو</h3><button type="button" onClick={onClose}><X/></button></div><input required value={name} onChange={e=>setName(e.target.value)} placeholder="اسم الغرفة" className="w-full rounded-xl border p-3 text-sm dark:bg-slate-900"/><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="الموضوع" className="w-full rounded-xl border p-3 text-sm dark:bg-slate-900"/><select value={maxParticipants} onChange={e=>setMax(Number(e.target.value))} className="w-full rounded-xl border p-3 text-sm dark:bg-slate-900">{[8,20,50].map(v=><option key={v} value={v}>{v} مستخدم</option>)}</select><button disabled={busy} className="w-full rounded-xl bg-black text-white py-3 font-bold disabled:opacity-50">{busy?'جاري الإنشاء...':'إنشاء الغرفة'}</button></form></div>;
};
