import {
  UserProfile,
  Note,
  NoteFolder,
  NoteTag,
  Expense,
  BudgetSummary,
  Vehicle,
  FuelRecord,
  MaintenanceRecord,
  Student,
  LessonItem,
  EducationExpense,
  Recipe,
  ShoppingItem,
  FavoritePlace,
  RecentTrip,
  SecureRecord,
  ChatRoom,
  ChatMessage,
  MediaFolder,
  MediaItem,
  AppNotification,
  AthkarItem,
  AiMessage,
  QuranWirdProgress,
  QuranAyah,
  ChristianPrayer,
  ChristianDailyReading,
} from '../types';

export const DEFAULT_USER: UserProfile = {
  id: 'usr_main_1',
  name: 'أحمد محمود',
  email: 'ahmed@smarttime.app',
  phone: '+20 100 123 4567',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  country: 'مصر',
  city: 'القاهرة',
  gender: 'male',
  occupation: 'مهندس برمجيات ورائد أعمال',
  currency: 'EGP',
  language: 'ar',
  theme: 'light',
  religiousPreference: 'islam',
  isOnboarded: true,
  pin: '1234',
  pinCode: '1234',
  biometricEnabled: true,
  birthDate: '1995-09-15',
  zodiacSign: 'العذراء',
  tickerPreferences: {
    showTimeAndDate: true,
    showGold: true,
    showSilver: true,
    showZodiac: true,
    showEgyptianLeague: true,
    showCrypto: true,
    showCurrencies: true,
    showWeather: true,
    showCustomMessage: true,
    customMessage: 'وقتك من ذهب ⏳ استثمر يومك في طاعة الله والإنجاز',
    favoriteEgyptianTeam: 'الأهلي',
    silverUnit: '999',
    goldUnit: '24',
  },
  vehiclePreferences: {
    primaryVehicleName: 'تويوتا كورولا 2023',
    fuelType: 'gasoline95',
    serviceIntervalKm: 10000,
  },
  budgetPreferences: {
    monthlyBudgetLimit: 25000,
    alertThresholdPercent: 80,
    defaultPaymentMethod: 'instapay',
  },
  religiousDetails: {
    reciter: 'الشيخ محمود خليل الحصري',
    prayerCalculationMethod: 'الهيئة المصرية العامة للمساحة',
    athkarReminderEnabled: true,
  },
  foodPreferences: {
    dietType: 'balanced',
    favoriteDish: 'كشري مصري بيتي وصينية بطاطس بالدجاج',
    autoAddToShoppingList: true,
  },
  educationPreferences: {
    defaultGradeLevel: 'الصف الثالث الإعدادي',
    homeworkAlerts: true,
  },
};

export const DEFAULT_NOTE_FOLDERS: NoteFolder[] = [
  { id: 'f_work', name: 'العمل والمشاريع', color: '#3b82f6', icon: 'Briefcase' },
  { id: 'f_personal', name: 'يوميات وأفكار', color: '#10b981', icon: 'User' },
  { id: 'f_finance', name: 'حسابات واستثمارات', color: '#f59e0b', icon: 'DollarSign' },
];

export const DEFAULT_NOTE_TAGS: NoteTag[] = [
  { id: 't_urgent', name: 'عاجل', color: '#ef4444' },
  { id: 't_idea', name: 'فكرة', color: '#8b5cf6' },
  { id: 't_meeting', name: 'اجتماع', color: '#06b6d4' },
];

export const DEFAULT_NOTES: Note[] = [
  {
    id: 'note_1',
    title: 'خطة إطلاق المشروع والمهام المالية',
    content: `<h3>أهم الأولويات لهذا الأسبوع:</h3>
<ul>
  <li><strong>مراجعة الميزانية الشهرية:</strong> التأكد من توزيع المصاريف بين الصيانة والتعليم.</li>
  <li><strong>اجتماع فريق العمل:</strong> مناقشة تقرير الربع السنوي والتحول الرقمي.</li>
  <li><strong>حجز موعد صيانة السيارة:</strong> تغيير الزيت وفحص الإطارات.</li>
</ul>
<blockquote><em>"وقتك من ذهب، كل دقيقة محسوبة هي خطوة نحو أهدافك."</em></blockquote>`,
    folderId: 'f_work',
    tags: ['t_urgent', 't_meeting'],
    color: '#ffffff',
    isFavorite: true,
    isArchived: false,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date().toISOString(),
    date: '2026-02-28',
  },
  {
    id: 'note_2',
    title: 'أفكار لتحسين النظام الغذائي والرياضة',
    content: `<p>الالتزام بنظام <strong>الطيبات / الكيتو</strong> المتوازن:</p>
<ol>
  <li>شرب 3 لتر ماء يوميًا.</li>
  <li>المشي 45 دقيقة بعد صلاة المغرب.</li>
  <li>التركيز على الدهون الصحية والبروتين وتجنب الزيوت المهدرجة.</li>
</ol>`,
    folderId: 'f_personal',
    tags: ['t_idea'],
    color: '#ffffff',
    isFavorite: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    updatedAt: new Date().toISOString(),
    date: '2026-02-27',
  },
];

export const DEFAULT_EXPENSES: Expense[] = [
  {
    id: 'exp_1',
    title: 'سوبرماركت ومشتريات البيت الأسبوعية',
    amount: 1450,
    category: 'food',
    date: new Date(Date.now() - 3600000 * 12).toISOString().split('T')[0],
    paymentMethod: 'card',
    notes: 'لحوم وخضروات ومكسرات صحية',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp_2',
    title: 'تفويلة بنزين 95 (تويوتا كورولا)',
    amount: 680,
    category: 'vehicle',
    date: new Date(Date.now() - 3600000 * 36).toISOString().split('T')[0],
    paymentMethod: 'wallet',
    notes: 'محطة شل - 45 لتر',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp_3',
    title: 'مصاريف مدرسة وكورسات لغات',
    amount: 2200,
    category: 'education',
    date: new Date(Date.now() - 3600000 * 72).toISOString().split('T')[0],
    paymentMethod: 'cash',
    notes: 'قسط الفصل الدراسي الثاني',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp_4',
    title: 'فاتورة الكهرباء والإنترنت المنزلي',
    amount: 850,
    category: 'bills',
    date: new Date(Date.now() - 3600000 * 96).toISOString().split('T')[0],
    paymentMethod: 'card',
    notes: 'دفع فوري أونلاين',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp_5',
    title: 'مشوار أوبر إلى المعادي',
    amount: 125,
    category: 'transport',
    date: new Date(Date.now() - 3600000 * 120).toISOString().split('T')[0],
    paymentMethod: 'wallet',
    notes: 'مشوار عمل عاجل',
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_BUDGET: BudgetSummary = {
  totalBudget: 18000,
  totalExpenses: 5305,
  remaining: 12695,
  percentUsed: 29.5,
};

export const DEFAULT_VEHICLES: Vehicle[] = [
  {
    id: 'veh_1',
    name: 'تويوتا كورولا (Toyota Corolla)',
    model: 'Corolla Active Plus',
    year: 2023,
    plateNumber: 'أ ب ج ٩٨٧٤',
    fuelType: '95',
    currentMileage: 28450,
    color: '#0284c7',
  },
  {
    id: 'veh_2',
    name: 'هيونداي إلنترا (Hyundai Elantra)',
    model: 'Elantra CN7',
    year: 2022,
    plateNumber: 'س ص ع ١٢٣٤',
    fuelType: '92',
    currentMileage: 46200,
    color: '#475569',
  },
];

export const DEFAULT_FUEL_RECORDS: FuelRecord[] = [
  {
    id: 'fuel_1',
    vehicleId: 'veh_1',
    liters: 45,
    pricePerLiter: 15.0,
    totalCost: 675,
    mileage: 28400,
    date: new Date(Date.now() - 3600000 * 40).toISOString().split('T')[0],
    stationName: 'شل مصر الجديدة',
    notes: 'تفويلة كاملة 95',
  },
  {
    id: 'fuel_2',
    vehicleId: 'veh_1',
    liters: 42,
    pricePerLiter: 15.0,
    totalCost: 630,
    mileage: 27900,
    date: new Date(Date.now() - 3600000 * 200).toISOString().split('T')[0],
    stationName: 'موبيل التجمع الخامس',
  },
];

export const DEFAULT_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  {
    id: 'maint_1',
    vehicleId: 'veh_1',
    systemType: 'oil',
    title: 'تغيير زيت المحرك 10,000 كم + فلتر الزيت الأصلي',
    cost: 1850,
    currentMileage: 25000,
    nextMileageDue: 35000,
    date: new Date(Date.now() - 3600000 * 400).toISOString().split('T')[0],
    serviceCenter: 'مركز الصيانة المعتمد',
    notes: 'زيت تويوتا التخليقي الكامل 5W-30',
  },
  {
    id: 'maint_2',
    vehicleId: 'veh_1',
    systemType: 'tires',
    title: 'ترصيص وتدوير الإطارات وضبط زوايا',
    cost: 450,
    currentMileage: 26000,
    nextMileageDue: 36000,
    date: new Date(Date.now() - 3600000 * 300).toISOString().split('T')[0],
    serviceCenter: 'بريدجستون فيت آند فيكس',
  },
  {
    id: 'maint_3',
    vehicleId: 'veh_1',
    systemType: 'battery',
    title: 'فحص البطارية والدينامو ونظافة الأقطاب',
    cost: 150,
    currentMileage: 27500,
    nextMileageDue: 45000,
    date: new Date(Date.now() - 3600000 * 100).toISOString().split('T')[0],
    serviceCenter: 'المهندس للكهرباء',
  },
];

export const DEFAULT_STUDENTS: Student[] = [
  {
    id: 'stud_1',
    name: 'يوسف أحمد',
    grade: 'الصف الأول الثانوي',
    schoolName: 'مدرسة النيل الدولية',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'stud_2',
    name: 'مريم أحمد',
    grade: 'الصف الخامس الابتدائي',
    schoolName: 'مدرسة المستقبل للغات',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
  },
];

export const DEFAULT_LESSONS: LessonItem[] = [
  {
    id: 'les_1',
    studentId: 'stud_1',
    subject: 'الرياضيات والفيزياء',
    title: 'حساب المثلثات والميكانيكا',
    dayOfWeek: 'الأحد والثلاثاء',
    time: '05:00 م - 07:00 م',
    tutorName: 'أ. طارق عبد الفتاح',
    monthlyFee: 800,
    isPaid: true,
  },
  {
    id: 'les_2',
    studentId: 'stud_1',
    subject: 'اللغة الإنجليزية',
    title: 'General English & IELTS Prep',
    dayOfWeek: 'الاثنين والخميس',
    time: '06:00 م - 07:30 م',
    tutorName: 'Mr. David Wilson',
    monthlyFee: 750,
    isPaid: false,
  },
  {
    id: 'les_3',
    studentId: 'stud_2',
    subject: 'العلوم والساينس',
    title: 'Living Systems & Energy',
    dayOfWeek: 'السبت والأربعاء',
    time: '04:00 م - 05:30 م',
    tutorName: 'ميس نورهان إبراهيم',
    monthlyFee: 600,
    isPaid: true,
  },
];

export const DEFAULT_EDUCATION_EXPENSES: EducationExpense[] = [
  {
    id: 'eduexp_1',
    studentId: 'stud_1',
    title: 'الكتب الخارجية وملازم المراجعة',
    amount: 650,
    category: 'books',
    date: new Date(Date.now() - 3600000 * 50).toISOString().split('T')[0],
  },
  {
    id: 'eduexp_2',
    studentId: 'stud_2',
    title: 'أدوات مدرسية وألوان للأنشطة',
    amount: 320,
    category: 'supplies',
    date: new Date(Date.now() - 3600000 * 120).toISOString().split('T')[0],
  },
];

export const DEFAULT_RECIPES: Recipe[] = [
  {
    id: 'rec_1',
    title: 'كشري مصري أصلي بالصلصة والدقة والتقلية',
    category: 'family',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    prepTimeMinutes: 25,
    cookTimeMinutes: 45,
    calories: 520,
    protein: 18,
    carbs: 88,
    fat: 9,
    ingredients: [
      { name: 'أرز مصري', amount: '2', unit: 'كوب' },
      { name: 'عدس بجبة بني', amount: '1.5', unit: 'كوب' },
      { name: 'مكرونة مقصوصة وإسباجيتي', amount: '350', unit: 'جرام' },
      { name: 'شعرية', amount: '1', unit: 'كوب' },
      { name: 'حمص الشام مسلوق', amount: '1', unit: 'كوب' },
      { name: 'بصل مقرمش (تقلية)', amount: '3', unit: 'حبات' },
      { name: 'طماطم معصورة وثوم وصلصة', amount: '500', unit: 'مل' },
      { name: 'خل وكمون وشطة للدقة', amount: '4', unit: 'ملاعق' },
    ],
    steps: [
      'سلق العدس بجبة في ماء مع رشة كمون حتى ينضج بنسبة 80%.',
      'تحمير البصل المقطع جوانح في زيت غزير حتى يصبح ذهبيًا ومقرمشًا وتصفيته.',
      'في نفس الزيت، تحمير الشعرية ثم إضافة الأرز والعدس ومائهما والتسوية على نار هادئة.',
      'سلق المكرونة في ماء مغلي مملح وتصفيتها وتغليفها بملعقة من زيت البصل.',
      'إعداد صلصة الطماطم بالثوم والخل والكمون، وتجهيز الدقة والشطة بالليمون والخل.',
      'تقديم الكشري طبقات: الأرز والعدس، ثم المكرونة، ثم الحمص والصلصة، وتتويجه بالبصل المقرمش.',
    ],
    isFavorite: true,
  },
  {
    id: 'rec_2',
    title: 'ستيك لحم أنتركوت بالزبدة والأعشاب (كيتو دايت)',
    category: 'keto',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    calories: 640,
    protein: 52,
    carbs: 2,
    fat: 48,
    ingredients: [
      { name: 'قطعة ستيك أنتركوت Ribeye', amount: '350', unit: 'جرام' },
      { name: 'زبدة طبيعية نقية', amount: '40', unit: 'جرام' },
      { name: 'فصوص ثوم طازجة مهروسة', amount: '4', unit: 'فصوص' },
      { name: 'روزماري وزعتر بري طازج', amount: '3', unit: 'أعواد' },
      { name: 'ملح بحري وفلفل أسود مجروش', amount: '1', unit: 'ملعقة صغيرة' },
    ],
    steps: [
      'إخراج اللحم من الثلاجة قبل الطهي بـ 30 دقيقة ليصبح بدرجة حرارة الغرفة.',
      'تجفيف سطح اللحم جيدًا وتتبيله بسخاء بالملح البحري والفلفل الأسود.',
      'تسخين مقلاة الحديد الزهر (Cast Iron) حتى تدخن خفيفًا مع ملعقة زيت زيتون بكر.',
      'وضع الستيك لمدة 3 دقائق دون تحريك، ثم قلبه على الوجه الآخر.',
      'إضافة الزبدة والثوم والروزماري والاستمرار في سكب الزبدة الذائبة فوق اللحم.',
      'ترك الستيك ليرتاح 5 دقائق قبل التقطيع للحفاظ على العصارة والنكهة.',
    ],
    isFavorite: true,
  },
  {
    id: 'rec_3',
    title: 'شوربة عظام البقر والمخ الطبيعية (نظام الطيبات)',
    category: 'tayyibat',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80',
    prepTimeMinutes: 15,
    cookTimeMinutes: 180,
    calories: 380,
    protein: 28,
    carbs: 4,
    fat: 26,
    ingredients: [
      { name: 'عظام بقر ونخاع طازجة', amount: '1.5', unit: 'كجم' },
      { name: 'خل تفاح طبيعي عضوي', amount: '2', unit: 'ملاعق كبيرة' },
      { name: 'بصل وجزر وكرفس بلدي', amount: '2', unit: 'حبات' },
      { name: 'حبهان ومستكة وورق لورا', amount: '1', unit: 'ملعقة' },
      { name: 'ملح صخري طبيعي وفلفل أسود', amount: '1.5', unit: 'ملعقة صغيرة' },
    ],
    steps: [
      'غسل العظام وشويها في الفرن 20 دقيقة لإكسابها نكهة غنية.',
      'وضع العظام في قدر كبير مع ماء مفلتر وخل التفاح وتركها 30 دقيقة لاستخلاص المعادن.',
      'رفع الشوربة على النار وإزالة أي رغوة تطفو على السطح.',
      'إضافة الخضروات والمستكة والحبهان وورق اللورا وتغطية القدر على نار هادئة جدًا 3 ساعات.',
      'تصفية المرقة الغنية بالكولاجين وشربها دافئة لترميم الأمعاء والمفاصل.',
    ],
    isFavorite: false,
  },
  {
    id: 'rec_4',
    title: 'صدر دجاج مشوي مع كينوا وخضار سوتيه (رياضيين)',
    category: 'sports',
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&auto=format&fit=crop&q=80',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    calories: 460,
    protein: 48,
    carbs: 42,
    fat: 10,
    ingredients: [
      { name: 'صدور دجاج مخلية', amount: '250', unit: 'جرام' },
      { name: 'كينوا مطبوخة', amount: '1', unit: 'كوب' },
      { name: 'بروكلي وفاصوليا خضراء وجزر', amount: '200', unit: 'جرام' },
      { name: 'زيت زيتون بكر ممتاز', amount: '1', unit: 'ملعقة كبيرة' },
      { name: 'ليمون وزعتر وبابريكا', amount: '1', unit: 'ملعقة صغيرة' },
    ],
    steps: [
      'تتبيل الدجاج بالليمون وزيت الزيتون والبابريكا والزعتر والملح.',
      'شواء الدجاج على جريل ساخن 6-7 دقائق لكل جانب حتى النضج الكامل.',
      'طهي الكينوا في ماء مملح بنسبة 1 كينوا إلى 2 ماء لمدة 15 دقيقة.',
      'تشويح الخضار السوتيه على البخار مع رشة زيت زيتون خفيفة.',
      'تقطيع الدجاج إلى شرائح وتقديمه بجانب الكينوا والخضار الملون.',
    ],
    isFavorite: false,
  },
];

export const DEFAULT_SHOPPING_ITEMS: ShoppingItem[] = [
  { id: 'shop_1', name: 'أرز مصري فاخر', quantity: 2, unit: 'كيلو', isCompleted: false, category: 'البقوليات والنشويات' },
  { id: 'shop_2', name: 'عدس بجبة بني', quantity: 1, unit: 'كيلو', isCompleted: true, category: 'البقوليات والنشويات' },
  { id: 'shop_3', name: 'زيت زيتون بكر معصور على البارد', quantity: 1, unit: 'لتر', isCompleted: false, category: 'الزيوت والدهون' },
  { id: 'shop_4', name: 'صدور دجاج طازجة', quantity: 1.5, unit: 'كيلو', isCompleted: false, category: 'اللحوم والدواجن' },
  { id: 'shop_5', name: 'خضار مشكل (بروكلي وجزر وطماطم)', quantity: 2, unit: 'كيلو', isCompleted: true, category: 'الخضروات والفواكه' },
  { id: 'shop_6', name: 'مكسرات مشكلة نيئة (لوز وجوز)', quantity: 500, unit: 'جرام', isCompleted: false, category: 'سناك صحي' },
];

export const DEFAULT_FAVORITE_PLACES: FavoritePlace[] = [
  {
    id: 'fav_home',
    title: 'المنزل (البيت)',
    type: 'home',
    point: { name: 'المنزل', address: 'مدينة نصر، القاهرة', lat: 30.0561, lng: 31.3301 },
  },
  {
    id: 'fav_work',
    title: 'العمل (الشركة)',
    type: 'work',
    point: { name: 'المقر الرئيسي', address: 'التجمع الخامس، القاهرة الجديدة', lat: 30.0131, lng: 31.4289 },
  },
  {
    id: 'fav_family',
    title: 'بيت العائلة',
    type: 'family',
    point: { name: 'منزل الوالدين', address: 'مصر الجديدة، القاهرة', lat: 30.0894, lng: 31.3285 },
  },
];

export const DEFAULT_RECENT_TRIPS: RecentTrip[] = [
  {
    id: 'rtrip_1',
    from: { name: 'المنزل (مدينة نصر)', address: 'شارع عباس العقاد', lat: 30.0561, lng: 31.3301 },
    to: { name: 'العمل (التجمع الخامس)', address: 'شارع التسعين الشمالي', lat: 30.0131, lng: 31.4289 },
    date: 'أمس 08:30 ص',
    provider: 'Uber Comfort',
    rideType: 'Comfort',
    fare: 115,
  },
  {
    id: 'rtrip_2',
    from: { name: 'ميدان التحرير', address: 'وسط البلد، القاهرة', lat: 30.0444, lng: 31.2357 },
    to: { name: 'مطار القاهرة الدولي صالة 3', address: 'مطار القاهرة', lat: 30.1219, lng: 31.4056 },
    date: 'منذ 3 أيام',
    provider: 'Uber X',
    rideType: 'Normal',
    fare: 185,
  },
];

export const DEFAULT_SECURE_RECORDS: SecureRecord[] = [
  {
    id: 'sec_photo_1',
    title: 'صورة شخصية سرية (بطاقة الرقم القومي والجواز)',
    category: 'photo',
    value: 'وثيقة هوية محمية',
    mediaUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
    fileName: 'passport_national_id_copy.jpg',
    fileSize: '1.8 MB',
    mimeType: 'image/jpeg',
    notes: 'صورة الهوية الوطنية وجواز السفر الساري حتى 2030',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sec_photo_2',
    title: 'صورة شخصية عائلية خاصة',
    category: 'photo',
    value: 'صورة عائلية مشفرة',
    mediaUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=800&auto=format&fit=crop&q=80',
    fileName: 'family_private_event.jpg',
    fileSize: '2.4 MB',
    mimeType: 'image/jpeg',
    notes: 'صورة خاصة من مناسبة عائلية',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sec_video_1',
    title: 'فيديو توثيق شخصي ومحمي',
    category: 'video',
    value: 'تسجيل مرئي مشفر',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    fileName: 'private_security_memo.mp4',
    fileSize: '14.2 MB',
    mimeType: 'video/mp4',
    notes: 'فيديو توثيق العقود والتسجيلات الخاصة',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sec_file_1',
    title: 'عقد ملكية الشقة والسيارة الرسمي (PDF)',
    category: 'file',
    value: 'عقد مسجل رسمي رقم 4982',
    mediaUrl: '',
    fileName: 'property_ownership_contract_2026.pdf',
    fileSize: '3.6 MB',
    mimeType: 'application/pdf',
    notes: 'نسخة رقمية مسجلة بالشهر العقاري',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sec_1',
    title: 'بطاقة البنك الأهلي المصري (الائتمانية)',
    category: 'bank_card',
    value: '5378 9200 4812 4892 (CVV: 843)',
    username: 'AHMED MAHMOUD',
    notes: 'صالحة حتى 09/28 - الحد الائتماني 50,000 ج.م',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sec_2',
    title: 'حساب العمل السحابي (Google Workspace)',
    category: 'password',
    value: 'Str0ng!Time#2026$',
    username: 'ahmed@smarttime.app',
    notes: 'تفعيل التحقق بخطوتين عبر الهاتف',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sec_3',
    title: 'أرقام الطوارئ وخدمة عملاء السيارات',
    category: 'phone',
    value: '16999 (ونش الإنقاذ السريع)',
    notes: 'متاح 24 ساعة على الطرق السريعة',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEFAULT_CHAT_ROOMS: ChatRoom[] = [
  {
    id: 'room_family',
    title: 'جروب العائلة 👨‍👩‍👧‍👦',
    name: 'جروب العائلة 👨‍👩‍👧‍👦',
    type: 'group',
    avatar: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=100&auto=format&fit=crop&q=80',
    lastMessage: 'يوسف: خلصت درس الرياضيات والحمد لله حليت الواجب!',
    lastMessageTime: '10:45 ص',
    unreadCount: 2,
    isOnline: true,
  },
  {
    id: 'room_work',
    title: 'فريق مشروع Smart Time 🚀',
    name: 'فريق مشروع Smart Time 🚀',
    type: 'group',
    avatar: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=100&auto=format&fit=crop&q=80',
    lastMessage: 'م. سارة: تم تحديث مواعيد التسليم ورفع الملفات.',
    lastMessageTime: '09:15 ص',
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: 'room_ai_assistant',
    title: 'Smart Time AI Bot 🤖',
    name: 'Smart Time AI Bot 🤖',
    type: 'direct',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    lastMessage: 'أنا جاهز لمساعدتك في أي استفسار أو تنظيم ليومك!',
    lastMessageTime: '08:00 ص',
    unreadCount: 0,
    isOnline: true,
  },
];

export const DEFAULT_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg_1',
    roomId: 'room_family',
    senderId: 'usr_sarah',
    senderName: 'سارة محمود',
    senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    text: 'صباح الخير جميعًا! لا تنسوا مراجعة قائمة المشتريات اليوم.',
    type: 'text',
    isOutgoing: false,
    timestamp: '09:00 ص',
  },
  {
    id: 'msg_2',
    roomId: 'room_family',
    senderId: 'usr_main_1',
    senderName: 'أحمد محمود',
    senderAvatar: DEFAULT_USER.avatarUrl,
    text: 'صباح النور يا سارة، ضفت مكونات الكشري والستيك في قائمة المشتريات وجارِ جلبها اليوم.',
    type: 'text',
    isOutgoing: true,
    timestamp: '09:12 ص',
  },
  {
    id: 'msg_3',
    roomId: 'room_family',
    senderId: 'usr_youssef',
    senderName: 'يوسف أحمد',
    senderAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&auto=format&fit=crop&q=80',
    text: 'خلصت درس الرياضيات والحمد لله حليت الواجب!',
    type: 'text',
    isOutgoing: false,
    timestamp: '10:45 ص',
  },
];

export const DEFAULT_MEDIA_FOLDERS: MediaFolder[] = [
  { id: 'm_receipts', name: 'فواتير وإيصالات رسمية', icon: '🧾', itemCount: 12 },
  { id: 'm_cars', name: 'وثائق ورخص السيارات', icon: '🚗', itemCount: 4 },
  { id: 'm_family', name: 'صور عائلية ورحلات', icon: '🖼️', itemCount: 35 },
  { id: 'm_docs', name: 'شهادات ومستندات PDF', icon: '📄', itemCount: 8 },
];

export const DEFAULT_MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'med_1',
    title: 'فاتورة صيانة تويوتا كورولا 25 ألف كم.pdf',
    name: 'فاتورة صيانة تويوتا كورولا 25 ألف كم.pdf',
    type: 'pdf',
    url: '',
    fileSize: '245 KB',
    sizeBytes: 245000,
    date: '2026-02-15',
    folderId: 'm_receipts',
    tags: ['صيانة', 'سيارة', 'تويوتا'],
  },
  {
    id: 'med_2',
    title: 'صورة رخصة قيادة سارية 2029.jpg',
    name: 'صورة رخصة قيادة سارية 2029.jpg',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&auto=format&fit=crop&q=80',
    fileSize: '1.2 MB',
    sizeBytes: 1240000,
    date: '2026-01-10',
    folderId: 'm_cars',
    tags: ['رخصة', 'مرور', 'رسمي'],
  },
  {
    id: 'med_3',
    title: 'جدول امتحانات الثانوية والمراجعات.pdf',
    name: 'جدول امتحانات الثانوية والمراجعات.pdf',
    type: 'pdf',
    url: '',
    fileSize: '480 KB',
    sizeBytes: 480000,
    date: '2026-02-20',
    folderId: 'm_docs',
    tags: ['تعليم', 'يوسف', 'مدرسة'],
  },
];

export const DEFAULT_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_chat_1',
    title: '💬 رسالة جديدة في جروب العائلة',
    body: 'سارة محمود: "صباح الخير جميعًا! لا تنسوا مراجعة قائمة المشتريات اليوم."',
    category: 'chat',
    date: 'منذ 15 دقيقة',
    isRead: false,
    actionTab: 'chat',
  },
  {
    id: 'notif_veh_1',
    title: '🚗 تذكير بصيانة السيارة الدورية',
    body: 'اقترب موعد فحص زيت تويوتا كورولا عند 35,000 كم (متبقي 550 كم).',
    category: 'vehicles',
    date: 'منذ ساعة',
    isRead: false,
    actionTab: 'vehicles',
  },
  {
    id: 'notif_trips_1',
    title: '📍 موعد مشوار مجدول',
    body: 'مشوار إلى: مطار القاهرة الدولي صالة 3 - وقت الانطلاق المقترح: 04:30 م.',
    category: 'trips',
    date: 'منذ ساعتين',
    isRead: false,
    actionTab: 'trips',
  },
  {
    id: 'notif_exp_1',
    title: '💰 تحديث الميزانية والمصروفات',
    body: 'تم تسجيل مصروف وقود بقيمة 675 ج.م. المتبقي من ميزانية الشهر 12,695 ج.م.',
    category: 'expenses',
    date: 'منذ 3 ساعات',
    isRead: false,
    actionTab: 'expenses',
  },
  {
    id: 'notif_rel_1',
    title: '🕌 اقتراب موعد صلاة العصر وأذكار المساء',
    body: 'متبقي 20 دقيقة على أذان العصر بتوقيت القاهرة. حان وقت أذكار المساء وورد القرآن.',
    category: 'religious',
    date: 'منذ 4 ساعات',
    isRead: false,
    actionTab: 'religious',
  },
  {
    id: 'notif_notes_1',
    title: '📝 ملاحظة مثبتة بانتظار المتابعة',
    body: 'مراجعة كشف حساب البنك الأهلي المصري وتوثيق دفع فواتير المرافق لشهر فبراير.',
    category: 'notes',
    date: 'منذ 5 ساعات',
    isRead: true,
    actionTab: 'notes',
  },
  {
    id: 'notif_edu_1',
    title: '🎓 متابعة دراسية: يوسف أحمد',
    body: 'تم حل واجب الرياضيات لمراجعة الجبر والتفاضل بنجاح وتقييم الأداء 95%.',
    category: 'education',
    date: 'أمس 07:30 م',
    isRead: true,
    actionTab: 'education',
  },
  {
    id: 'notif_food_1',
    title: '🛒 قائمة المشتريات والمطبخ',
    body: 'يوجد 4 أصناف بحاجة للشراء اليوم (لحم ستيك، خضروات طازجة، بهارات كشري).',
    category: 'food',
    date: 'أمس 04:00 م',
    isRead: true,
    actionTab: 'food',
  },
  {
    id: 'notif_sec_1',
    title: '🔒 تنبيه الخزنة الرقمية الآمنة',
    body: 'تم قفل الخزنة الرقمية وتشفير المستندات وكلمات المرور بنجاح.',
    category: 'security',
    date: 'منذ يومين',
    isRead: true,
    actionTab: 'vault',
  },
  {
    id: 'notif_sys_1',
    title: '☁️ اكتمال النسخ الاحتياطي للنظام',
    body: 'تم حفظ نسخة احتياطية محلية مشفرة لجميع بيانات البرنامج تلقائيًا بنجاح.',
    category: 'backup',
    date: 'منذ يومين',
    isRead: true,
    actionTab: 'backup',
  },
];

export const DEFAULT_ATHKAR: AthkarItem[] = [
  {
    id: 'athk_1',
    categoryId: 'morning',
    text: 'أَصْبَحْنَا وَأَصْبَحَ المُلْكُ لِلَّهِ، وَالحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ المُلْكُ وَلَهُ الحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ.',
    repeatCount: 1,
    currentCount: 0,
    virtue: 'حفظ وبركة طوال اليوم',
  },
  {
    id: 'athk_2',
    categoryId: 'morning',
    text: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ.',
    repeatCount: 1,
    currentCount: 0,
  },
  {
    id: 'athk_3',
    categoryId: 'morning',
    text: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ: عَدَدَ خَلْقِهِ، وَرِضَا نَفْسِهِ، وَزِنَةَ عَرْشِهِ، وَمِدَادَ كَلِمَاتِهِ.',
    repeatCount: 3,
    currentCount: 0,
    virtue: 'تعدل عبادة ساعات طويلة',
  },
  {
    id: 'athk_4',
    categoryId: 'morning',
    text: 'بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ العَلِيمُ.',
    repeatCount: 3,
    currentCount: 0,
    virtue: 'لم يضره شيء حتى يمسي',
  },
  {
    id: 'athk_5',
    categoryId: 'evening',
    text: 'أَمْسَيْنَا وَأَمْسَى المُلْكُ لِلَّهِ، وَالحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ.',
    repeatCount: 1,
    currentCount: 0,
  },
  {
    id: 'athk_6',
    categoryId: 'evening',
    text: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ.',
    repeatCount: 3,
    currentCount: 0,
    virtue: 'حماية وحصن من كل سوء',
  },
  {
    id: 'athk_7',
    categoryId: 'tasbeeh',
    text: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ',
    repeatCount: 33,
    currentCount: 0,
    virtue: 'كلمتان خفيفتان على اللسان ثقيلتان في الميزان',
  },
  {
    id: 'athk_8',
    categoryId: 'tasbeeh',
    text: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ وَأَتُوبُ إِلَيْهِ',
    repeatCount: 100,
    currentCount: 0,
    virtue: 'مغفرة للذنوب وتفريج للكروب وسعة في الرزق',
  },
];

export const DEFAULT_AI_MESSAGES: AiMessage[] = [
  {
    id: 'ai_1',
    sender: 'ai',
    text: 'مرحبًا بك في مركز الذكاء الاصطناعي الفائق لتطبيق SMART TIME! أنا مساعدك الذكي المتكامل، كيف يمكنني خدمتك اليوم؟',
    timestamp: '09:00 ص',
    model: 'gemini-2.5-flash',
  },
];

export const DEFAULT_QURAN_WIRD_PROGRESS: QuranWirdProgress = {
  currentPage: 45,
  totalPages: 604,
  dailyGoalPages: 4,
  currentSurahName: 'سورة البقرة (الجزء الثالث)',
  reminderTime: '06:30 ص',
  reminderEnabled: true,
  streakDays: 12,
  lastReadDate: new Date().toISOString().split('T')[0],
};

export const DEFAULT_QURAN_AYAH_TOPICS: QuranAyah[] = [
  {
    numberInSurah: 53,
    surahNumber: 39,
    surahName: 'الزمر',
    text: 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ',
    juzNumber: 24,
    topicColor: 'green',
    topicLabelAr: 'الرحمة والمغفرة والرجاء 💚',
    tafsir: 'دعوة للتائبين بعدم اليأس من رحمة الله العظيمة الشاملة لكل الذنوب لمن تاب وأناب.',
  },
  {
    numberInSurah: 255,
    surahNumber: 2,
    surahName: 'البقرة',
    text: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ...',
    juzNumber: 3,
    topicColor: 'blue',
    topicLabelAr: 'العقيدة والتوحيد وأسماء الله 💙',
    tafsir: 'أعظم آية في كتاب الله تبين كمال وحدانية الله وقدرته وحفظه للكون.',
  },
  {
    numberInSurah: 183,
    surahNumber: 2,
    surahName: 'البقرة',
    text: 'يَا أَيُّهَا الَّذِينَ آمَنُوا كُتِبَ عَلَيْكُمُ الصِّيَامُ كَمَا كُتِبَ عَلَى الَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ',
    juzNumber: 2,
    topicColor: 'yellow',
    topicLabelAr: 'الأحكام والعبادات والمعاملات 💛',
    tafsir: 'فرض صيام شهر رمضان لتحقيق التقوى وتزكية النفس.',
  },
  {
    numberInSurah: 133,
    surahNumber: 3,
    surahName: 'آل عمران',
    text: 'وَسَارِعُوا إِلَىٰ مَغْفِرَةٍ مِّن رَّبِّكُمْ وَجَنَّةٍ عَرْضُهَا السَّمَاوَاتُ وَالْأَرْضُ أُعِدَّتْ لِلْمُتَّقِينَ',
    juzNumber: 4,
    topicColor: 'purple',
    topicLabelAr: 'الجنة والنعيم والترغيب 💜',
    tafsir: 'حث المؤمنين على المسارعة في الخيرات لنيل جنة النعيم المقيم.',
  },
  {
    numberInSurah: 10,
    surahNumber: 12,
    surahName: 'يوسف',
    text: 'قَالَ قَائِلٌ مِّنْهُمْ لَا تَقْتُلُوا يُوسُفَ وَأَلْقُوهُ فِي غَيَابَتِ الْجُبِّ يَلْتَقِطْهُ بَعْضُ السَّيَّارَةِ إِن كُنتُمْ فَاعِلِينَ',
    juzNumber: 12,
    topicColor: 'red',
    topicLabelAr: 'قصص الأنبياء والعبر 🧡',
    tafsir: 'بداية ابتلاء نبي الله يوسف عليه السلام وتدبير الله ولطفه به حتى التمكين.',
  },
];

export const DEFAULT_CHRISTIAN_PRAYERS: ChristianPrayer[] = [
  {
    id: 'pr_baker',
    title: 'صلاة باكر 🌅',
    hourName: 'الساعة الأولى من النهار',
    description: 'تُقام تذكاراً لقيامة الرب يسوع المسيح من بين الأموات والنور الحقيقي للعالم.',
    text: 'هلم نسجد ونركع للمسيح ملكنا وإلهنا. يا رب اسمع صلاتي، وانصت إلى طلبتي بحقك. استجب لي بعدلك، ولا تدخل في المحاكمة مع عبدك، فإنه لن يتزكى قدامك أي حي.',
  },
  {
    id: 'pr_ghoroub',
    title: 'صلاة الغروب (الساعة الحادية عشرة) 🌇',
    hourName: 'وقت غروب الشمس',
    description: 'تذكار إنزال جسد الرب يسوع من على الصليب وشكر على نعمة اليوم.',
    text: 'نشكرك يا ضابط الكل، لأنك جزت بنا هذا النهار بسلام وأتيت بنا إلى المساء شاكرين. أهلنا يا رب أن نرضيك في هذا المساء وكل أيام حياتنا.',
  },
  {
    id: 'pr_noom',
    title: 'صلاة النوم 🌙',
    hourName: 'الساعة الثانية عشرة',
    description: 'تذكار وضع جسد المخلص في القبر وطلب الحماية والسلام الروحي أثناء النوم.',
    text: 'أيها الرب إلهنا، الذي أعطانا النوم راحة لضعف جسدنا، نجنا من كل دنس واسترنا بظل جناحيك، واحفظنا في هذه الليلة بسلام وطهارة.',
  },
  {
    id: 'pr_nesf_leil',
    title: 'صلاة نصف الليل ⭐',
    hourName: 'السهر والاستعداد',
    description: 'تذكار المجئ الثاني للرب يسوع وسهر العذارى الحكيمات.',
    text: 'قوموا يا بني النور لنسبح رب القوات، لكي ينعم علينا بخلاص نفوسنا. هوذا العريس يأتي في نصف الليل، فطوبى للعبد الذي يجده مستيقظاً.',
  },
];

export const DEFAULT_CHRISTIAN_DAILY_READING: ChristianDailyReading = {
  date: new Date().toISOString().split('T')[0],
  saintOfDay: 'تذكار القديس مار مرقس الرسول كاروز الديار المصرية',
  thoughtOfDay: '«المَحَبَّةُ لاَ تَسْقُطُ أَبَداً» (1 كو 13: 8) - عش يومك بالمحبة والوداعة والسلام مع الجميع.',
  gospelReference: 'إنجيل متى 5: 1-12 (الموعظة على الجبل)',
  gospelText: '«طُوبَى لِلْمَسَاكِينِ بِالرُّوحِ، لأَنَّ لَهُمْ مَلَكُوتَ السَّمَاوَاتِ. طُوبَى لِلْحَزَانَى، لأَنَّهُمْ يُعَزَّوْنَ. طُوبَى لِلْوُدَعَاءِ، لأَنَّهُمْ يَرِثُونَ الأَرْضَ. طُوبَى لِلْجِيَاعِ وَالعِطَاشِ إِلَى البِرِّ، لأَنَّهُمْ يُشْبَعُونَ. طُوبَى لِلرُّحَمَاءِ، لأَنَّهُمْ يُرْحَمُونَ. طُوبَى لِلأَنْقِيَاءِ القَلْبِ، لأَنَّهُمْ يُعَايِنُونَ اللهَ. طُوبَى لِصَانِعِي السَّلاَمِ، لأَنَّهُمْ أَبْنَاءَ اللهِ يُدْعَوْنَ.»',
  epistleReference: 'رسالة بولس الرسول الأولى إلى أهل كورنثوس 13',
  epistleText: '«إِنْ كُنْتُ أَتَكَلَّمُ بِأَلْسِنَةِ النَّاسِ وَالمَلاَئِكَةِ وَلكِنْ لَيْسَ لِي مَحَبَّةٌ، فَقَدْ صِرْتُ نُحَاساً يَطِنُّ أَوْ صَنْجاً يَرِنُّ. المَحَبَّةُ تَتَأَنَّى وَتَرْفُقُ. المَحَبَّةُ لاَ تَحْسِدُ...»',
};

