export const STORAGE_KEYS = {
  USER_PROFILE: 'smart_time_user_profile',
  NOTES: 'smart_time_notes',
  NOTE_FOLDERS: 'smart_time_note_folders',
  NOTE_TAGS: 'smart_time_note_tags',
  CALCULATOR_HISTORY: 'smart_time_calc_history',
  DAILY_TASKS: 'smart_time_daily_tasks',
  EXPENSES: 'smart_time_expenses',
  BUDGET: 'smart_time_budget',
  MONTHLY_INCOME: 'smart_time_monthly_income',
  BANK_CERTIFICATES: 'smart_time_bank_certificates',
  VEHICLES: 'smart_time_vehicles',
  FUEL_RECORDS: 'smart_time_fuel_records',
  MAINTENANCE_RECORDS: 'smart_time_maint_records',
  ACCIDENT_RECORDS: 'smart_time_accident_records',
  STUDENTS: 'smart_time_students',
  LESSONS: 'smart_time_lessons',
  EDUCATION_EXPENSES: 'smart_time_edu_expenses',
  FAVORITE_PLACES: 'smart_time_favorite_places',
  RECENT_TRIPS: 'smart_time_recent_trips',
  SECURE_RECORDS: 'smart_time_secure_records',
  CHAT_ROOMS: 'smart_time_chat_rooms',
  CHAT_MESSAGES: 'smart_time_chat_messages',
  MEDIA_FOLDERS: 'smart_time_media_folders',
  MEDIA_ITEMS: 'smart_time_media_items',
  NOTIFICATIONS: 'smart_time_notifications',
  ATHKAR_ITEMS: 'smart_time_athkar_items',
  AI_CHAT_HISTORY: 'smart_time_ai_chat_history',
  NOTIFICATION_SOUND: 'smart_time_notification_sound',
  DASHBOARD_LAYOUT: 'smart_time_dashboard_layout',
  DASHBOARD_SECTIONS_V2: 'smart_time_dashboard_sections_v2',
  WORKOUT_LOGS: 'smart_time_workout_logs',
  SPORTS_CARDS_ORDER: 'smart_time_sports_cards_order',
  EXPENSES_SECTIONS_ORDER: 'smart_time_expenses_sections_order',
} as const;
\nexport const STORAGE_KEY_MIGRATIONS = {\n  smart_time_dashboard_layout: STORAGE_KEYS.DASHBOARD_LAYOUT,\n  smart_time_dashboard_sections_v2: STORAGE_KEYS.DASHBOARD_SECTIONS_V2,\n  smart_time_workout_logs: STORAGE_KEYS.WORKOUT_LOGS,\n  smart_time_sports_cards_order: STORAGE_KEYS.SPORTS_CARDS_ORDER,\n  smart_time_expenses_sections_order: STORAGE_KEYS.EXPENSES_SECTIONS_ORDER,\n} as const;\n