import React, { useMemo, useState } from 'react';
import { ArrowRight, ArrowLeft, BarChart3, FileSpreadsheet, FileText, Printer, Home, UserRound, Users, Car, GraduationCap, WalletCards, Layers, X, Eye } from 'lucide-react';
import { formatMoney } from '../../services/financeCalculations';
import { Language } from '../../types';

interface Props { language:Language; currency:string; selectedMonth:string; onSelectMonth:(month:string)=>void; onBack:()=>void; monthlyIncome:number; monthlyExpenses:number; netIncome:number; houseTotal:number; workTotal:number; vehicleTotal:number; educationTotal:number; houseList?:any[]; medicalList?:any[]; personalList?:any[]; associationsList?:any[]; fuelList?:any[]; maintList?:any[]; oilFilterList?:any[]; accidentList?:any[]; studentExpensesList?:any[]; students?:any[]; incomeList?:any[]; }
type ReportType='day'|'week'|'month'; type SectionKey='all'|'income'|'house'|'personal'|'associations'|'vehicle'|'education';
interface Row{date:string;section:string;item:string;amount:number;details?:string;}
const addMonths=(date:string,n:number)=>{const d=new Date(date+'T12:00:00');const x=new Date(d.getFullYear(),d.getMonth()+n,d.getDate());return x.toISOString().slice(0,10)};
const monthDiff=(a:string,b:string)=>{const x=new Date(a+'T12:00:00'),y=new Date(b+'T12:00:00');return (y.getFullYear()-x.getFullYear())*12+y.getMonth()-x.getMonth()};
const assocRows=(a:any,from:string,to:string,add:(d:string,s:string,i:string,v:number,det?:string)=>void)=>{if(!a.startDate)return;const start=a.startDate.slice(0,10),payout=(a.payoutDate||'').slice(0,10);let d=start;let count=0;while(d<=to && count<Math.max(1,Number(a.memberCount)||1)){if(d>=from)add(d,'جمعياتى',`${a.name} - القسط رقم ${count+1}`,-(Number(a.installment)||0),`من بداية الأقساط ${start}`);count++;d=addMonths(start,count);}if(payout>=from&&payout<=to)add(payout,'جمعياتى',`${a.name} - قبض الجمعية`,Number(a.value)||0,`استحقاق الدور رقم ${a.roleNumber||''}`)};
export const FinancialReportsSection:React.FC<Props>=p=>{
 const {language,currency,onBack,monthlyIncome,monthlyExpenses,netIncome,houseTotal,workTotal,vehicleTotal,educationTotal,houseList=[],medicalList=[],personalList=[],associationsList=[],fuelList=[],maintList=[],oilFilterList=[],accidentList=[],studentExpensesList=[],students=[],incomeList=[]}=p;
 const isAr=language==='ar',BackIcon=isAr?ArrowRight:ArrowLeft; const [section,setSection]=useState<SectionKey>('all'); const [reportType,setReportType]=useState<ReportType>('month'); const [fromDate,setFromDate]=useState(`${new Date().getFullYear()}-01-01`); const [toDate,setToDate]=useState(new Date().toISOString().slice(0,10)); const [dayDate,setDayDate]=useState(''); const [previewOpen,setPreviewOpen]=useState(false);
 const cards=[{id:'income' as const,title:'الدخل الشهري',icon:WalletCards,total:monthlyIncome,desc:'تفاصيل مصادر الدخل'},{id:'house' as const,title:'مصروفات منزلية والقسم الطبي',icon:Home,total:houseTotal,desc:'المنزل والكشوفات والأدوية'},{id:'personal' as const,title:'الإنفاق الشخصى',icon:UserRound,total:workTotal,desc:'تفاصيل الإنفاق الشخصي'},{id:'associations' as const,title:'جمعياتى',icon:Users,total:0,desc:'كل الأقساط والقبض'},{id:'vehicle' as const,title:'سيارتى',icon:Car,total:vehicleTotal,desc:'وقود وصيانة وزيوت وحوادث'},{id:'education' as const,title:'التعليم',icon:GraduationCap,total:educationTotal,desc:'تفاصيل مصروفات الطلاب'},{id:'all' as const,title:'التقرير الشامل',icon:Layers,total:netIncome,desc:'كل الحركات المالية بالتفصيل'}];
 const effectiveFrom=reportType==='day'&&dayDate?dayDate:fromDate; const effectiveTo=reportType==='day'&&dayDate?dayDate:toDate;
 const daysInRange=useMemo(()=>{const arr:string[]=[];let d=effectiveFrom;let guard=0;while(d<=effectiveTo&&guard<370){arr.push(d);d=addMonths(d,0);const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+1);d=x.toISOString().slice(0,10);guard++}return arr},[effectiveFrom,effectiveTo]);
 const rows=useMemo<Row[]>(()=>{const out:Row[]=[];const from=effectiveFrom,to=effectiveTo;const add=(date:string,s:string,i:string,v:number,details?:string)=>{const d=(date||'').slice(0,10);if(d>=from&&d<=to)out.push({date:d,section:s,item:i,amount:Number(v)||0,details});};
  if(section==='house'||section==='all'){houseList.forEach(x=>add(x.date,'مصروفات منزلية',x.type||'مصروف منزلي',-Math.abs(Number(x.amount)||0),x.notes));medicalList.forEach(x=>add(x.date,'القسم الطبي',`${x.familyMember||'فرد الأسرة'} - ${x.facilityType||'كشف'}`,-((Number(x.examinationCost)||0)+(Number(x.medicationCost)||0)),`الحالة: ${x.conditionDescription||'—'} • التشخيص: ${x.doctorDiagnosis||'—'} • الجهة: ${x.facilityName||'—'}`));}
  if(section==='personal'||section==='all')personalList.forEach(x=>add(x.date,'الإنفاق الشخصى',x.type||'إنفاق شخصي',-Math.abs(Number(x.amount)||0),x.notes));
  if(section==='associations'||section==='all')associationsList.forEach(a=>assocRows(a,from,to,add));
  if(section==='vehicle'||section==='all'){fuelList.forEach(x=>add(x.dateTime,'سيارتى - الوقود',x.fuelType||'وقود',-Math.abs(Number(x.price)||0),x.odometer?`عداد ${x.odometer}`:''));maintList.forEach(x=>add(x.date,'سيارتى - الصيانة',x.maintenanceType||'صيانة',-Math.abs(Number(x.total)||0),x.description));oilFilterList.forEach(x=>add(x.date,'سيارتى - الزيوت والفلاتر',x.serviceType||'خدمة',-Math.abs(Number(x.price)||0),x.productName));accidentList.forEach(x=>add(x.date,'سيارتى - الحوادث','حادث / إصلاح',-Math.abs(Number(x.estimatedDamage)||0),x.description));}
  if(section==='education'||section==='all')studentExpensesList.forEach(x=>{const s=students.find(st=>st.id===x.studentId);add(x.date,'التعليم',`${s?.name||'طالب'} - ${x.title||x.subCategory||'مصروف تعليمي'}`,-Math.abs(Number(x.amount)||0),s?`المرحلة: ${s.stage} • العمر: ${s.age}`:'')});
  if(section==='income'||section==='all')incomeList.forEach(x=>{const d=`${x.month}-01`;add(d,'الدخل الشهري','الراتب',Number(x.salary)||0);add(d,'الدخل الشهري','المكافآت',Number(x.bonuses)||0);add(d,'الدخل الشهري','دخل آخر',Number(x.otherIncome)||0);(x.sources||[]).forEach((src:any)=>{if(src.type==='current_deposit'||src.type==='current_withdrawal')add(src.date||d,'الحساب الجاري',src.source||'معاملة بنكية',Number(src.amount)||0,src.notes)});});
  return out.sort((a,b)=>b.date.localeCompare(a.date));},[section,effectiveFrom,effectiveTo,houseList,medicalList,personalList,associationsList,fuelList,maintList,oilFilterList,accidentList,studentExpensesList,students,incomeList]);
 const title=reportType==='day'?'تقرير يومى':reportType==='week'?'تقرير أسبوعى':'تقرير شهرى'; const total=rows.reduce((s,r)=>s+r.amount,0);
 const csv=()=>{const data=[['التاريخ','القسم','البيان','المبلغ','التفاصيل'],...rows.map(r=>[r.date,r.section,r.item,String(r.amount),r.details||''])];const blob=new Blob(['\uFEFF'+data.map(r=>r.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`smart-time-${section}-${reportType}-${effectiveFrom}-${effectiveTo}.csv`;a.click()};
 const word=()=>{const html=`<html dir="rtl"><meta charset="utf-8"><body><h1>SMART TIME - ${title}</h1><p>القسم: ${cards.find(c=>c.id===section)?.title}</p><p>الفترة: ${effectiveFrom} إلى ${effectiveTo}</p><table border="1" cellpadding="7" cellspacing="0" style="width:100%;border-collapse:collapse"><tr><th>التاريخ</th><th>القسم</th><th>البيان</th><th>المبلغ</th><th>التفاصيل</th></tr>${rows.map(r=>`<tr><td>${r.date}</td><td>${r.section}</td><td>${r.item}</td><td>${formatMoney(r.amount)} ${currency}</td><td>${r.details||'—'}</td></tr>`).join('')}</table><h3>إجمالي الحركات: ${formatMoney(total)} ${currency}</h3></body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff',html],{type:'application/msword'}));a.download=`smart-time-${section}-${reportType}.doc`;a.click()};
 return <div className="space-y-4" dir={isAr?'rtl':'ltr'}><div className="bg-white dark:bg-slate-900 p-4 rounded-2xl border shadow-sm flex items-center gap-3"><button onClick={onBack} className="w-10 h-10 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center"><BackIcon/></button><div className="w-10 h-10 rounded-xl bg-cyan-50 text-cyan-600 flex items-center justify-center"><BarChart3/></div><div><h1 className="text-lg font-black">تقاريرى</h1><p className="text-xs text-slate-500">اختر القسم والفترة ونوع التقرير ثم عاين التفاصيل قبل التصدير</p></div></div>
 <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="sm:col-span-2"><label className="text-xs font-bold block mb-1">من تاريخ</label><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} className="w-full p-3 rounded-xl border bg-white dark:bg-slate-900"/></div><div className="sm:col-span-2"><label className="text-xs font-bold block mb-1">إلى تاريخ</label><input type="date" value={toDate} min={fromDate} onChange={e=>setToDate(e.target.value)} className="w-full p-3 rounded-xl border bg-white dark:bg-slate-900"/></div></div>
 <div className="bg-white dark:bg-slate-900 p-4 rounded-2xl border shadow-sm"><label className="text-xs font-bold block mb-2">نوع التقرير</label><select value={reportType} onChange={e=>setReportType(e.target.value as ReportType)} className="w-full p-3 rounded-xl border bg-slate-50 dark:bg-slate-800"><option value="day">تقرير يومى</option><option value="week">تقرير أسبوعى</option><option value="month">تقرير شهرى</option></select>{reportType==='day'&&<><label className="text-xs font-bold block mt-3 mb-2">اختر اليوم داخل الفترة</label><select value={dayDate||fromDate} onChange={e=>setDayDate(e.target.value)} className="w-full p-3 rounded-xl border bg-slate-50 dark:bg-slate-800">{daysInRange.map(d=><option key={d} value={d}>{d}</option>)}</select></>}</div>
 <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{cards.map(c=>{const I=c.icon;return <button key={c.id} onClick={()=>setSection(c.id)} className={`text-right bg-white dark:bg-slate-900 p-4 rounded-2xl border shadow-sm ${section===c.id?'border-cyan-500 ring-2 ring-cyan-100':'border-slate-200 dark:border-slate-800'}`}><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-cyan-50 text-cyan-600 flex items-center justify-center"><I/></div><div><b className="text-sm block">{c.title}</b><span className="text-[10px] text-slate-500">{c.desc}</span></div></div></button>})}</div>
 <button onClick={()=>setPreviewOpen(true)} className="w-full py-3 rounded-2xl bg-slate-900 text-white font-black flex items-center justify-center gap-2"><Eye/>معاينة التقرير بالتفصيل</button>
 {previewOpen&&<div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-3"><div className="bg-white dark:bg-slate-900 rounded-3xl w-full max-w-6xl max-h-[92vh] overflow-hidden"><div className="p-4 border-b flex justify-between items-center"><div><b>{title} — {cards.find(c=>c.id===section)?.title}</b><div className="text-xs text-slate-500 mt-1">الفترة: {effectiveFrom} إلى {effectiveTo} • {rows.length} حركة</div></div><button onClick={()=>setPreviewOpen(false)}><X/></button></div><div className="p-4 overflow-auto max-h-[68vh]">{rows.length===0?<div className="p-12 text-center text-slate-400">لا توجد حركات تفصيلية في الفترة المحددة.</div>:<table className="w-full text-xs border-collapse"><thead><tr className="bg-slate-100 dark:bg-slate-800"><th className="p-2 text-right">التاريخ</th><th className="p-2 text-right">القسم</th><th className="p-2 text-right">البيان</th><th className="p-2 text-right">المبلغ</th><th className="p-2 text-right">التفاصيل</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-b"><td className="p-2">{r.date}</td><td className="p-2">{r.section}</td><td className="p-2 font-bold">{r.item}</td><td className={`p-2 font-black ${r.amount>=0?'text-emerald-600':'text-rose-600'}`}>{r.amount>=0?'+':''}{formatMoney(r.amount)} {currency}</td><td className="p-2 text-slate-500">{r.details||'—'}</td></tr>)}</tbody></table>}</div><div className="p-4 border-t flex flex-wrap gap-2"><div className="px-4 py-3 rounded-xl bg-slate-100 font-black text-xs">إجمالي الحركات: {formatMoney(total)} {currency}</div><button onClick={csv} className="px-4 py-3 rounded-xl bg-emerald-600 text-white font-bold text-xs"><FileSpreadsheet className="inline w-4 h-4 ml-1"/>Excel</button><button onClick={word} className="px-4 py-3 rounded-xl bg-blue-600 text-white font-bold text-xs"><FileText className="inline w-4 h-4 ml-1"/>Word</button><button onClick={()=>window.print()} className="px-4 py-3 rounded-xl bg-slate-800 text-white font-bold text-xs"><Printer className="inline w-4 h-4 ml-1"/>طباعة / PDF</button></div></div></div>}
 </div>;
};
