import React, { useMemo, useState } from 'react';
import { Download, Edit, FileSpreadsheet, FileText, Printer, Trash2, X } from 'lucide-react';
import { BankCertificate, CertificateProfitFrequency, Language, MonthlyIncome } from '../types';
import { ExpensesRepository } from '../services';

interface Props { language: Language; currency: string; }
const monthKey = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; };
const num = (n:number) => n.toLocaleString('en-US',{maximumFractionDigits:2});
const esc = (v:unknown) => String(v ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');

export const IncomeCertificatesView: React.FC<Props> = ({ language, currency }) => {
  const isAr = language === 'ar';
  const [tab,setTab] = useState<'income'|'certificates'|'reports'>('income');
  const [income,setIncome] = useState<MonthlyIncome[]>(()=>ExpensesRepository.getMonthlyIncome());
  const [certificates,setCertificates] = useState<BankCertificate[]>(()=>ExpensesRepository.getBankCertificates());
  const [selectedMonth,setSelectedMonth] = useState(monthKey());
  const [salary,setSalary] = useState(''); const [bonuses,setBonuses] = useState(''); const [otherIncome,setOtherIncome] = useState(''); const [otherNote,setOtherNote] = useState(''); const [editingIncome,setEditingIncome] = useState<string|null>(null);
  const [bankName,setBankName] = useState(''); const [certificateNumber,setCertificateNumber] = useState(''); const [duration,setDuration] = useState(''); const [amount,setAmount] = useState(''); const [issueDate,setIssueDate] = useState(''); const [maturityDate,setMaturityDate] = useState(''); const [profitDate,setProfitDate] = useState(''); const [profitAmount,setProfitAmount] = useState(''); const [profitFrequency,setProfitFrequency] = useState<CertificateProfitFrequency>('monthly'); const [certificateNotes,setCertificateNotes] = useState(''); const [editingCertificate,setEditingCertificate] = useState<string|null>(null);

  const profitForMonth = (month:string) => certificates.reduce((sum,c) => {
    if (!c.profitAmount) return sum;
    const start = c.profitDate.slice(0,7), end = c.maturityDate.slice(0,7);
    if (c.profitFrequency === 'monthly') return start <= month && month <= end ? sum + c.profitAmount : sum;
    return start === month ? sum + c.profitAmount : sum;
  },0);
  const selected = income.find(x=>x.month===selectedMonth);
  const selectedProfit = profitForMonth(selectedMonth);
  const selectedTotal = (selected?.salary||0)+(selected?.bonuses||0)+(selected?.otherIncome||0)+selectedProfit;
  const reportRows = useMemo(()=>income.map(i=>({month:i.month,salary:i.salary,bonuses:i.bonuses,other:i.otherIncome,profits:profitForMonth(i.month),total:i.salary+i.bonuses+i.otherIncome+profitForMonth(i.month)})).sort((a,b)=>b.month.localeCompare(a.month)),[income,certificates]);

  const saveIncome=(e:React.FormEvent)=>{ e.preventDefault(); const item:MonthlyIncome={id:editingIncome||`income_${Date.now()}`,month:selectedMonth,salary:Number(salary)||0,bonuses:Number(bonuses)||0,otherIncome:Number(otherIncome)||0,otherIncomeNote:otherNote.trim()||undefined,createdAt:editingIncome?(selected?.createdAt||new Date().toISOString()):new Date().toISOString(),updatedAt:new Date().toISOString()}; const next=editingIncome?income.map(x=>x.id===editingIncome?item:x):[item,...income.filter(x=>x.month!==selectedMonth)]; setIncome(next);ExpensesRepository.saveMonthlyIncome(next);setEditingIncome(null);setSalary('');setBonuses('');setOtherIncome('');setOtherNote(''); };
  const editIncome=(x:MonthlyIncome)=>{setSelectedMonth(x.month);setSalary(String(x.salary));setBonuses(String(x.bonuses));setOtherIncome(String(x.otherIncome));setOtherNote(x.otherIncomeNote||'');setEditingIncome(x.id);setTab('income');};
  const deleteIncome=(id:string)=>{const next=income.filter(x=>x.id!==id);setIncome(next);ExpensesRepository.saveMonthlyIncome(next);};
  const resetCertificate=()=>{setBankName('');setCertificateNumber('');setDuration('');setAmount('');setIssueDate('');setMaturityDate('');setProfitDate('');setProfitAmount('');setProfitFrequency('monthly');setCertificateNotes('');setEditingCertificate(null);};
  const saveCertificate=(e:React.FormEvent)=>{e.preventDefault();if(!bankName.trim()||!duration.trim()||Number(amount)<=0||!issueDate||!maturityDate||!profitDate)return;const item:BankCertificate={id:editingCertificate||`cert_${Date.now()}`,bankName:bankName.trim(),certificateNumber:certificateNumber.trim()||undefined,duration:duration.trim(),amount:Number(amount),issueDate,maturityDate,profitDate,profitAmount:Number(profitAmount)||0,profitFrequency,notes:certificateNotes.trim()||undefined,createdAt:editingCertificate?(certificates.find(c=>c.id===editingCertificate)?.createdAt||new Date().toISOString()):new Date().toISOString(),updatedAt:new Date().toISOString()};const next=editingCertificate?certificates.map(c=>c.id===editingCertificate?item:c):[item,...certificates];setCertificates(next);ExpensesRepository.saveBankCertificates(next);resetCertificate();};
  const editCertificate=(c:BankCertificate)=>{setBankName(c.bankName);setCertificateNumber(c.certificateNumber||'');setDuration(c.duration);setAmount(String(c.amount));setIssueDate(c.issueDate);setMaturityDate(c.maturityDate);setProfitDate(c.profitDate);setProfitAmount(String(c.profitAmount||''));setProfitFrequency(c.profitFrequency);setCertificateNotes(c.notes||'');setEditingCertificate(c.id);setTab('certificates');};
  const deleteCertificate=(id:string)=>{const next=certificates.filter(c=>c.id!==id);setCertificates(next);ExpensesRepository.saveBankCertificates(next);};

  const exportReport=(kind:'csv'|'excel'|'word'|'print')=>{
    const headers=['الشهر','الراتب','المكافآت','دخل آخر','أرباح الشهادات','إجمالي الدخل'];
    const rows=reportRows.map(r=>[r.month,r.salary,r.bonuses,r.other,r.profits,r.total]);
    const certRows=certificates.map(c=>[c.bankName,c.certificateNumber||'',c.duration,c.amount,c.issueDate,c.maturityDate,c.profitDate,c.profitAmount,c.profitFrequency]);
    if(kind==='csv'){const text='\uFEFF'+[headers.join(','),...rows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')),'','البنك,رقم الشهادة,المدة,القيمة,الإصدار,الاستحقاق,نزول الأرباح,قيمة الأرباح,الدورية',...certRows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=`smart-time-financial-report-${selectedMonth}.csv`;a.click();return;}
    const html=`<html dir="rtl"><head><meta charset="utf-8"><title>SMART TIME - التقرير المالي</title><style>body{font-family:Arial;padding:30px}h1,h2{text-align:center}table{width:100%;border-collapse:collapse;margin:18px 0}th,td{border:1px solid #999;padding:8px;text-align:center}th{background:#eee}</style></head><body><h1>SMART TIME — التقرير المالي</h1><h2>الدخل الشهري</h2><table><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</table><h2>الشهادات البنكية</h2><table><tr>${['البنك','رقم الشهادة','المدة','القيمة','الإصدار','الاستحقاق','نزول الأرباح','قيمة الأرباح','الدورية'].map(h=>`<th>${h}</th>`).join('')}</tr>${certRows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</table></body></html>`;
    if(kind==='print'){const w=window.open('','_blank','width=1100,height=800');if(w){w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),300);}return;}
    const ext=kind==='word'?'doc':'xls';const mime=kind==='word'?'application/msword':'application/vnd.ms-excel';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:mime}));a.download=`smart-time-financial-report-${selectedMonth}.${ext}`;a.click();
  };

  return <div className="space-y-5">
    <div className="flex flex-wrap gap-2 bg-[#161616] p-1.5 rounded-2xl border border-slate-800">
      <button onClick={()=>setTab('income')} className={`flex-1 min-w-[150px] py-3 rounded-xl font-bold text-xs ${tab==='income'?'bg-gradient-to-r from-accent-500 to-accent-700 text-slate-950':'text-slate-400 hover:bg-slate-800'}`}>💰 الدخل الشهري</button>
      <button onClick={()=>setTab('certificates')} className={`flex-1 min-w-[150px] py-3 rounded-xl font-bold text-xs ${tab==='certificates'?'bg-gradient-to-r from-accent-500 to-accent-700 text-slate-950':'text-slate-400 hover:bg-slate-800'}`}>🏦 شهادات البنوك</button>
      <button onClick={()=>setTab('reports')} className={`flex-1 min-w-[150px] py-3 rounded-xl font-bold text-xs ${tab==='reports'?'bg-gradient-to-r from-accent-500 to-accent-700 text-slate-950':'text-slate-400 hover:bg-slate-800'}`}>📊 التقارير</button>
    </div>

    {tab==='income' && <div className="grid lg:grid-cols-12 gap-5">
      <div className="lg:col-span-5 bg-[#1a1a1a] p-5 rounded-3xl border border-accent-500/30"><div className="flex justify-between mb-4"><h3 className="font-black text-white">💰 تسجيل الدخل الشهري</h3>{editingIncome&&<button onClick={()=>{setEditingIncome(null);setSalary('');setBonuses('');setOtherIncome('');setOtherNote('')}}><X className="w-4 h-4 text-slate-400"/></button>}</div>
        <form onSubmit={saveIncome} className="space-y-3"><label className="block text-xs font-bold text-slate-300">الشهر<input type="month" required value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)} className="mt-1 w-full p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"/></label><label className="block text-xs font-bold text-slate-300">الراتب<input type="number" min="0" step="0.01" value={salary} onChange={e=>setSalary(e.target.value)} className="mt-1 w-full p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"/></label><label className="block text-xs font-bold text-slate-300">المكافآت<input type="number" min="0" step="0.01" value={bonuses} onChange={e=>setBonuses(e.target.value)} className="mt-1 w-full p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"/></label><label className="block text-xs font-bold text-slate-300">دخل آخر<input type="number" min="0" step="0.01" value={otherIncome} onChange={e=>setOtherIncome(e.target.value)} className="mt-1 w-full p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"/></label><label className="block text-xs font-bold text-slate-300">تفاصيل الدخل الآخر (اختياري)<input value={otherNote} onChange={e=>setOtherNote(e.target.value)} className="mt-1 w-full p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"/></label><button className="w-full py-3 rounded-xl bg-accent-500 text-slate-950 font-black">{editingIncome?'تحديث الدخل':'حفظ الدخل'}</button></form>
      </div>
      <div className="lg:col-span-7 space-y-4"><div className="grid grid-cols-2 lg:grid-cols-3 gap-3"><div className="p-4 rounded-2xl bg-[#1a1a1a] border border-slate-800"><span className="text-[10px] text-slate-400">الدخل الأساسي</span><div className="text-lg font-black text-white">{num((selected?.salary||0)+(selected?.bonuses||0)+(selected?.otherIncome||0))} {currency}</div></div><div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20"><span className="text-[10px] text-slate-400">أرباح الشهادات</span><div className="text-lg font-black text-emerald-400">{num(selectedProfit)} {currency}</div></div><div className="col-span-2 lg:col-span-1 p-4 rounded-2xl bg-accent-500/10 border border-accent-500/30"><span className="text-[10px] text-accent-300">إجمالي الدخل الشهري</span><div className="text-xl font-black text-accent-500">{num(selectedTotal)} {currency}</div></div></div>
        <div className="bg-[#1a1a1a] rounded-3xl border border-slate-800 overflow-hidden"><div className="p-4 border-b border-slate-800 font-black text-white">السجلات المحفوظة</div>{income.length===0?<div className="p-8 text-center text-slate-500">لا توجد سجلات دخل</div>:income.slice().sort((a,b)=>b.month.localeCompare(a.month)).map(r=><div key={r.id} className="p-3 border-b border-slate-800 flex justify-between items-center"><div><b className="text-white">{r.month}</b><div className="text-[10px] text-slate-400">{num(r.salary+r.bonuses+r.otherIncome+profitForMonth(r.month))} {currency} شامل أرباح الشهادات</div></div><div className="flex gap-1"><button onClick={()=>editIncome(r)} className="p-2 text-accent-500"><Edit className="w-4 h-4"/></button><button onClick={()=>deleteIncome(r.id)} className="p-2 text-rose-400"><Trash2 className="w-4 h-4"/></button></div></div>)}</div>
      </div>
    </div>}

    {tab==='certificates' && <div className="grid lg:grid-cols-12 gap-5">
      <div className="lg:col-span-5 bg-[#1a1a1a] p-5 rounded-3xl border border-accent-500/30"><div className="flex justify-between mb-4"><h3 className="font-black text-white">🏦 {editingCertificate?'تعديل شهادة':'إضافة شهادة بنكية'}</h3>{editingCertificate&&<button onClick={resetCertificate}><X className="w-4 h-4"/></button>}</div>
        <form onSubmit={saveCertificate} className="grid grid-cols-2 gap-3 text-xs">{[ ['اسم البنك',bankName,setBankName,true,'text'],['رقم الشهادة',certificateNumber,setCertificateNumber,false,'text'],['مدة الشهادة',duration,setDuration,true,'text'],['قيمة الشهادة',amount,setAmount,true,'number'] ].map(([label,value,setter,required,type]:any)=><label key={label} className="font-bold text-slate-300">{label}{required?' *':''}<input required={required} type={type} min={type==='number'?'0':undefined} value={value} onChange={e=>setter(e.target.value)} className="mt-1 w-full p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"/></label>)}
          {[ ['تاريخ الإصدار',issueDate,setIssueDate],['تاريخ الاستحقاق',maturityDate,setMaturityDate],['تاريخ نزول الأرباح',profitDate,setProfitDate],['قيمة الأرباح',profitAmount,setProfitAmount] ].map(([label,value,setter]:any)=><label key={label} className="font-bold text-slate-300">{label}{label==='قيمة الأرباح'?'':' *'}<input required={label!=='قيمة الأرباح'} type={label==='قيمة الأرباح'?'number':'date'} min={label==='قيمة الأرباح'?'0':undefined} value={value} onChange={e=>setter(e.target.value)} className="mt-1 w-full p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"/></label>)}
          <label className="font-bold text-slate-300">دورية الأرباح<select value={profitFrequency} onChange={e=>setProfitFrequency(e.target.value as CertificateProfitFrequency)} className="mt-1 w-full p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"><option value="monthly">شهرية</option><option value="quarterly">ربع سنوية</option><option value="semiannual">نصف سنوية</option><option value="annual">سنوية</option><option value="maturity">عند الاستحقاق</option></select></label><label className="font-bold text-slate-300">ملاحظات<textarea value={certificateNotes} onChange={e=>setCertificateNotes(e.target.value)} className="mt-1 w-full p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"/></label><button className="col-span-2 py-3 rounded-xl bg-accent-500 text-slate-950 font-black">{editingCertificate?'حفظ التعديل':'حفظ الشهادة'}</button>
        </form>
      </div>
      <div className="lg:col-span-7 bg-[#1a1a1a] p-5 rounded-3xl border border-slate-800"><div className="p-4 rounded-2xl bg-accent-500/10 border border-accent-500/20 mb-4"><span className="text-[10px] text-slate-400">إجمالي قيمة الشهادات</span><div className="text-2xl font-black text-accent-500">{num(certificates.reduce((s,c)=>s+c.amount,0))} {currency}</div></div><div className="space-y-2 max-h-[620px] overflow-auto">{certificates.length===0?<div className="p-10 text-center text-slate-500">لا توجد شهادات</div>:certificates.map(c=><div key={c.id} className="p-4 rounded-2xl bg-slate-900 border border-slate-800 flex justify-between gap-3"><div><div className="font-black text-white">{c.bankName}</div><div className="text-[10px] text-slate-400 mt-1">{c.certificateNumber||'بدون رقم'} • {c.duration} • {num(c.amount)} {currency}</div><div className="text-[10px] text-slate-400 mt-1">إصدار: {c.issueDate} • استحقاق: {c.maturityDate} • نزول الأرباح: {c.profitDate}</div><div className="text-[10px] text-emerald-400 mt-1">الأرباح: {num(c.profitAmount)} {currency} • {c.profitFrequency}</div></div><div className="flex gap-1"><button onClick={()=>editCertificate(c)} className="p-2 text-accent-500"><Edit className="w-4 h-4"/></button><button onClick={()=>deleteCertificate(c.id)} className="p-2 text-rose-400"><Trash2 className="w-4 h-4"/></button></div></div>)}</div></div>
    </div>}

    {tab==='reports' && <div className="space-y-5"><div className="bg-[#1a1a1a] p-5 rounded-3xl border border-accent-500/30"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h3 className="text-lg font-black text-white">📊 التقرير المالي</h3><p className="text-xs text-slate-400">إجمالي الدخل الشهري = الراتب + المكافآت + إجمالي الدخل الآخر + أرباح الشهادات</p></div><input type="month" value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)} className="p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white"/></div><div className="mt-5 p-5 rounded-2xl bg-accent-500/10 border border-accent-500/30"><span className="text-xs text-accent-300">إجمالي دخل الشهر المحدد</span><div className="text-3xl font-black text-accent-500">{num(selectedTotal)} {currency}</div></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>exportReport('excel')} className="px-4 py-2.5 rounded-xl bg-emerald-600 text-white font-bold text-xs flex gap-2"><FileSpreadsheet className="w-4 h-4"/> Excel</button><button onClick={()=>exportReport('word')} className="px-4 py-2.5 rounded-xl bg-blue-600 text-white font-bold text-xs flex gap-2"><FileText className="w-4 h-4"/> Word</button><button onClick={()=>exportReport('csv')} className="px-4 py-2.5 rounded-xl bg-slate-800 text-white font-bold text-xs flex gap-2"><Download className="w-4 h-4"/> CSV</button><button onClick={()=>exportReport('print')} className="px-4 py-2.5 rounded-xl bg-accent-500 text-slate-950 font-bold text-xs flex gap-2"><Printer className="w-4 h-4"/> طباعة / PDF</button></div><div className="bg-[#1a1a1a] rounded-3xl border border-slate-800 overflow-auto"><table className="w-full text-xs"><thead><tr className="border-b border-slate-800 text-slate-400"><th className="p-3">الشهر</th><th className="p-3">الراتب</th><th className="p-3">المكافآت</th><th className="p-3">دخل آخر</th><th className="p-3">أرباح الشهادات</th><th className="p-3">إجمالي الدخل</th></tr></thead><tbody>{reportRows.map(r=><tr key={r.month} className="border-b border-slate-800"><td className="p-3 font-bold text-white">{r.month}</td><td className="p-3">{num(r.salary)}</td><td className="p-3">{num(r.bonuses)}</td><td className="p-3">{num(r.other)}</td><td className="p-3 text-emerald-400">{num(r.profits)}</td><td className="p-3 font-black text-accent-500">{num(r.total)} {currency}</td></tr>)}</tbody></table></div></div>}
  </div>;
};
